AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Admin Group, User, and MFA Policy

Resources:
  AdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: admin-group
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  AdminUser:
    Type: AWS::IAM::User
    Properties:
      UserName: admin-user
      Groups:
        - !Ref AdminGroup

  AdminUserMFA:
    Type: AWS::IAM::UserPolicy
    Properties:
      UserName: !Ref AdminUser
      PolicyName: enforce-mfa
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Deny
            Action: '*'
            Resource: '*'
            Condition:
              BoolIfExists:
                aws:MultiFactorAuthPresent: 'false'